spring.application.name=dentistry-data-analysis


# ?? ?? ?? ?? (?: 10MB)
spring.servlet.multipart.max-file-size=100MB
# ?? ?? ?? ?? (?: 20MB)
spring.servlet.multipart.max-request-size=100MB


data.storage.path=/home/dentusr/data_analysis/CRF

#위에가 파일질라, 밑에는 로컬

data.storage.folderPath=/Dental_Archive
#data.storage.folderPath=/치의학데이터 과제 데이터 수집/내부 데이터/단국대

server.port=8081


 #원광대서버 환경 SFTP 설정
sftp.server.host=210.126.75.11
sftp.server.port=2024
sftp.server.user=master01
sftp.server.password=Master01!!!

## 시놀로지 환경 SFTP 설정 테스트용
#sftp.server.host=202.86.11.27
#sftp.server.port=22
#sftp.server.user=dent_fas
#sftp.server.password=dent_fas123